#security
spring.security.user.name=test
spring.security.user.password=test
jwt.secret=korisnickoime
server.error.include-message=always
server.address=0.0.0.0
server.port=8081
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=keystore
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=sslkeystore
#database
spring.datasource.url=jdbc:postgresql://localhost:5432/projekatbaza
spring.datasource.username=postgres
spring.datasource.password=Miroslav02
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#email
spring.mail.host=smtp.gmail.com
spring.mail.username=savamander@gmail.com
spring.mail.password=lozinka
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mvc.dispatch-options-request=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.security.oauth2.client.registration.keycloak.client-id=booking-app
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9090/realms/TestRealm1
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/TestRealm1