#security
spring.security.user.name=test
spring.security.user.password=test
jwt.secret=8dae84f846e4f4b158a8d26681707f4338495bc7ab68151d7f7679cc5e56202dd3da0d356da007a7c28cb0b780418f4f3246769972d6feaa8f610c7d1e7ecf6a
server.error.include-message=always
server.address=192.168.100.3
server.port=8080
#database
spring.datasource.url=jdbc:postgresql://localhost:5432/projekatbaza
spring.datasource.username=postgres
spring.datasource.password=Miroslav02
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#email
spring.mail.host=smtp.gmail.com
spring.mail.username=savamander@gmail.com
spring.mail.password=sadsad
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

