#security
spring.security.user.name=test
spring.security.user.password=test
jwt.secret=korisnickoime

server.error.include-message=always

#database
spring.datasource.url=jdbc:postgresql://localhost:5432/projekatbaza
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect